### ISSUE TITLE
Adding extra jdoc tags

### ISSUE THREAD

**Issue by yuretz** [Wikunia/brackets-FuncDocr#62] opened 2015-07-08 09:26 UTC
Hello,
When I add extra jsdoc tags, for example  `@throws {Error} Will throw if something is wrong`,
the line sometimes gets indented wrong, so that `@throws` is aligned with previous annotation description text. It seems it only happen if previous annotation text was wrapped. Is there a way to avoid this behavior? 
Right now I'm just manually re-indenting those lines, but it gets annoying pretty soon, so I decided to try and ask here :)

Thanks!

BR, Yuriy

**Comment by Wikunia** [comment] 2015-07-19 11:15
Hey,

sorry for my late response :/ Can you provide a simple example?

**Comment by yuretz** [comment] 2015-07-19 18:28
Yes, sure.

Please see the image below:
![Indentation bug](http://i.imgur.com/vozhUz8.gif)

So, what happens in this case, is that I'm wrapping the long line by hitting 'Enter' and then trying to re-indent it by hitting 'Tab'. 
Maybe there were some other cases, when it behaved similarly, but right now I can't remember.
FuncDocr 0.8.26, Brackets 1.3

**Comment by Wikunia** [comment] 2015-07-22 14:37
Hmm thanks, yeah I think I will need some time to solve it. Thanks for the issue and stay tuned!

**Comment by Wikunia** [comment] 2015-07-29 09:20
Hi @yuretz 
this one is the new version which isn't good as well :/
![brackets-funcdocr- 62](https://cloud.githubusercontent.com/assets/4931746/8953986/d35d41de-35e2-11e5-9740-e2a17413be46.png)
The problem is that I have a maximum padding which aligns the descriptions but probably you would like to see something like this?
![brackets-funcdocr- 62-opt2](https://cloud.githubusercontent.com/assets/4931746/8954059/64b0b2ce-35e3-11e5-8434-1ccb23165033.png)

Or the third option would be:
![brackets-funcdocr- 62-opt3](https://cloud.githubusercontent.com/assets/4931746/8954099/99568882-35e3-11e5-96a3-6129a4ad936c.png)

FYI the current implementation of `@throws` is:
`"throws": "@throws [[Description]]",`
there is no name field for the name of the error.

**Comment by Wikunia** [comment] 2015-07-30 16:23
Maybe you would like to test the newest version `0.8.27` (Install from url)

**Comment by yuretz** [comment] 2015-07-30 19:40
Hi Wikunia,
Thanks for your replies. I'll definitely try it tomorrow. Would I be able to install it directly from the repo url?

**Comment by Wikunia** [comment] 2015-07-30 19:41
Yes it is in the master branch

**Comment by yuretz** [comment] 2015-08-01 23:12
Hi again,

Thanks for the new version. It's really nice to see that small (but very useful) things like FuncDocr get their deal of support and attention!

I have tested the new version a little bit. It seems like it solves part of the issue, but not all of it. And you are probably right, this looks like a more complex general problem with manual editing of auto-generated comments.

When I add `@throws`, or any other jsdoc tag after existing auto-generated tags, what I do is
* I place the cursor at the end of the line, after which I would like to add my new tag and hit 'enter' to add an empty line. If, for example, previous line was `@param {type} name description`, the cursor gets aligned with the description start on the previous line. And that's fine and totally make sense at this point.
* I start typing `@throws`, auto-completion menu appears amd I choose `@throws [[Description]]` template. It is inserted, but it stays aligned with the previous line description and that of course doesn't make sense anymore.
* I manually delete indentation  before `@throws` to make it aligned properly with other tags and then hit 'Tab' to navigate to the missing [[Description]] placeholder, and the line gets wrongly re-aligned again.

Regarding the solution, it's hard to tell which one is the best. There is no doubt that all `@<tag_name>` parts should be aligned in the start. From there, as I see it, you have two options:
1. Align the rest of the fields in columns by fields' relative position. Like, 1st field is always in the first column after the tag, 2nd is in the 2nd and so on. This one is probably the easiest option.
2. Align the rest of the fields in columns, taking into account the field purpose. Like, all names get their own separate column, all type names get their separate column, all textual descriptions too, and so on. This will probably look better, but might be more difficult to implement, eats more screen space for indentation. 
 
As for me, I could definitely live with any of those options implemented, as long as manual re-indentation is not necessary to make it look reasonable.

BTW, would it be possible to support both `@throws` template with and without exception type included?

**Comment by Wikunia** [comment] 2015-08-02 10:41
Again version v0.8.27 ;) Would be great if you would install it from url!
Changes:
- The tags will be sorted now so `@throws` and `@this` will be shown at the top and not `@author`, when typing `@th` :D
- the wrong alignment on tabbing should be fixed now
- the cursor is aligned under `[[Description]]` and you include a `@` tag it will be on the most left side

Thanks for your support.
With the current implementation two hints for `@throws` aren't possible because I might want to use the number of `[[...]]` for a specified tag for alignment which isn't easily possible with two different implementations for `@throws`.
But I think `@throws` should have always an exception type, right? Then it's better documented I think ;)

**Comment by yuretz** [comment] 2015-08-04 06:58
Hi,
Thanks for the updated version. I'm testing it right now, and it looks good so far.
I agree that having documentation with explicit exception types is much better than without them. I personally always use it with the type.

**Comment by Wikunia** [comment] 2015-08-04 07:02
Okay and then it will look like `@throws {[[ExType]]} [[Description]]` and `ExType` can be filled if the syntax `throw new UserException("...");` is used right?

**Comment by yuretz** [comment] 2015-08-04 09:35
Exactly!

**Comment by Wikunia** [comment] 2017-07-13 01:42
Hi @yuretz ,
It's 2017 now and wow just read our small conversation again. Looks like I can close this issue, right?
Otherwise just reopen it! ;)

**Closed by Wikunia** 2017-07-13 01:42 UTC

**Comment by yuretz** [comment] 2017-07-13 21:20
Sure, thank you!
